/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.consolaentrada.views;

import com.mxrck.autocompleter.TextAutoCompleter;
import com.soltelec.consolaentrada.models.controllers.ClaseVehiculoJpaController;
import com.soltelec.consolaentrada.models.controllers.Datos;
import com.soltelec.consolaentrada.models.controllers.LineaVehiculoJpaController;
import com.soltelec.consolaentrada.models.controllers.MarcaJpaController;
import com.soltelec.consolaentrada.models.controllers.ServicioJpaController;
import com.soltelec.consolaentrada.models.controllers.TipoVehiculoJpaController;
import com.soltelec.consolaentrada.models.entities.ClaseVehiculo;
import com.soltelec.consolaentrada.models.entities.LineaVehiculo;
import com.soltelec.consolaentrada.models.entities.Marca;
import com.soltelec.consolaentrada.models.entities.ParametrosBusqueda;
import com.soltelec.consolaentrada.models.entities.Servicio;
import com.soltelec.consolaentrada.models.entities.TipoVehiculo;
import com.soltelec.consolaentrada.utilities.Mensajes;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author User
 */
public class CriteriosBusqueda extends javax.swing.JFrame {

    private TextAutoCompleter textAutoAcompleterTipo;
    private TextAutoCompleter textAutoAcompleterMarca;
    private TextAutoCompleter textAutoAcompletercClase;
    private TextAutoCompleter textAutoAcompleterServicio;
    private TextAutoCompleter textAutoAcompleterLinea;
    private PanelImpresionByFecha byFecha;

    /**
     * Creates new form CriteriosBusqueda
     */
    public CriteriosBusqueda(PanelImpresionByFecha byFecha) {
        initComponents();
        cmbEstado.setVisible(false);
        lbl_estado.setVisible(false);
        cargarLista();
        this.byFecha = byFecha;
        dteFechaFinal.setDate(null);
        dteFechaInicial.setDate(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        cmbCilindraje = new javax.swing.JComboBox();
        cmbModelo = new javax.swing.JComboBox();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtCilindraje = new javax.swing.JTextField();
        txtNumeroMotor = new javax.swing.JTextField();
        txtVin = new javax.swing.JTextField();
        txtNumeroLicencia = new javax.swing.JTextField();
        txtNumeroEjes = new javax.swing.JTextField();
        txtLinea = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtClase = new javax.swing.JTextField();
        txtServicio = new javax.swing.JTextField();
        txtIdPropietario = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbl_estado = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        dteFechaInicial = new JXDatePicker(new Date(),new Locale("es"));
        dteFechaInicial.setFormats(new String[]{"dd/MM/yyyy"});
        dteFechaFinal = new JXDatePicker(new Date(),new Locale("es"));
        dteFechaInicial.setFormats(new String[]{"dd/MM/yyyy"});
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setForeground(java.awt.Color.lightGray);

        jLabel9.setBackground(java.awt.Color.lightGray);
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Servicio:");
        jLabel9.setOpaque(true);

        cmbCilindraje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">" }));

        cmbModelo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "<", ">" }));

        txtMarca.setToolTipText("");

        txtTipo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTipoFocusGained(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Aceptar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel17.setBackground(java.awt.Color.lightGray);
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Nùmero de ejes:");
        jLabel17.setOpaque(true);

        jLabel18.setBackground(java.awt.Color.lightGray);
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Marca:");
        jLabel18.setOpaque(true);

        jLabel19.setBackground(java.awt.Color.lightGray);
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Tipo Vehiculo:");
        jLabel19.setOpaque(true);

        jLabel20.setBackground(java.awt.Color.lightGray);
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Cilindraje:");
        jLabel20.setOpaque(true);

        jLabel21.setBackground(java.awt.Color.lightGray);
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Clase Vehiculo:");
        jLabel21.setOpaque(true);

        jLabel22.setBackground(java.awt.Color.lightGray);
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Linea Vehiculo:");
        jLabel22.setOpaque(true);

        jLabel23.setBackground(java.awt.Color.lightGray);
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Placa:");
        jLabel23.setOpaque(true);

        jLabel24.setBackground(java.awt.Color.lightGray);
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Modelo:");
        jLabel24.setOpaque(true);

        jLabel25.setBackground(java.awt.Color.lightGray);
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Marca:");
        jLabel25.setOpaque(true);

        jLabel26.setBackground(java.awt.Color.lightGray);
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Numero Motor:");
        jLabel26.setOpaque(true);

        jLabel27.setBackground(java.awt.Color.lightGray);
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("VIN:");
        jLabel27.setOpaque(true);

        jLabel28.setBackground(java.awt.Color.lightGray);
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Identificacòn Propietario:");
        jLabel28.setOpaque(true);

        jLabel29.setBackground(java.awt.Color.lightGray);
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Apellido Propietario:");
        jLabel29.setOpaque(true);

        jLabel30.setBackground(java.awt.Color.lightGray);
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("Nombre Propietario:");
        jLabel30.setOpaque(true);

        jLabel32.setBackground(java.awt.Color.lightGray);
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("Nùmero de licencia:");
        jLabel32.setOpaque(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Busqueda Avanzada");

        lbl_estado.setBackground(java.awt.Color.lightGray);
        lbl_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_estado.setText("Estado");
        lbl_estado.setOpaque(true);
        lbl_estado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_estadoMouseClicked(evt);
            }
        });

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "APROBADA", "REPROBADA", "PENDIENTE" }));

        dteFechaInicial.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dteFechaInicial.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        dteFechaInicial.setPreferredSize(new java.awt.Dimension(180, 40));

        dteFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dteFechaFinal.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        dteFechaFinal.setPreferredSize(new java.awt.Dimension(180, 40));

        jLabel33.setBackground(java.awt.Color.lightGray);
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("Fecha Inicial:");
        jLabel33.setOpaque(true);

        jLabel34.setBackground(java.awt.Color.lightGray);
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Fecha FInal:");
        jLabel34.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 693, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4)
                                    .addComponent(txtModelo))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(9, 9, 9)
                                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmbCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtCilindraje)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtNumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtIdPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtNumeroEjes, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(9, 9, 9)
                                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdPropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroLicencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroEjes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCilindraje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTipoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTipoFocusGained

    }//GEN-LAST:event_txtTipoFocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Integer d;
        ParametrosBusqueda busqueda = new ParametrosBusqueda();
        busqueda.setApellido(txtApellido.getText());

        if (!txtCilindraje.getText().isEmpty()) {
            busqueda.setCmbcilindraje(cmbCilindraje.getSelectedItem().toString());
            busqueda.setCilindraje(Integer.parseInt(txtCilindraje.getText()));
        } else {
            busqueda.setCilindraje(0);
        }
        if (textAutoAcompletercClase.getItemSelected() != null && !txtClase.getText().isEmpty()) {
            Datos datosClase = ((Datos) textAutoAcompletercClase.findItem(txtClase.getText()));
            if (!datosClase.getNombre().isEmpty() && datosClase.getId() > 0) {
                busqueda.setClase(datosClase.getId());
            }
        } else {
            busqueda.setClase(0);
        }
        if (textAutoAcompleterLinea.getItemSelected() != null && !txtLinea.getText().isEmpty()) {
            Datos dd = ((Datos) textAutoAcompleterLinea.findItem(txtLinea.getText()));
            if (!dd.getNombre().isEmpty() && dd.getId() > 0) {
                busqueda.setLinea(dd.getId());
            }
        } else {
            busqueda.setLinea(0);
        }
        if (textAutoAcompleterMarca.getItemSelected() != null && !txtMarca.getText().isEmpty()) {
            Datos datosMarca = ((Datos) textAutoAcompleterMarca.findItem(txtMarca.getText()));
            if (!datosMarca.getNombre().isEmpty() && datosMarca.getId() > 0) {
                busqueda.setMarca(datosMarca.getId());
            }
        } else {
            busqueda.setMarca(0);
        }
        if (!txtModelo.getText().isEmpty()) {
            busqueda.setCmbModelo(cmbModelo.getSelectedItem().toString());
            busqueda.setModelo(Integer.parseInt(txtModelo.getText()));
        }
        if (!txtCilindraje.getText().isEmpty()) {
            busqueda.setCmbModelo(cmbModelo.getSelectedItem().toString());
            busqueda.setCilindraje(Integer.parseInt(txtCilindraje.getText()));
        }
        busqueda.setNombre(txtNombres.getText());
        if (!txtNumeroEjes.getText().isEmpty()) {
            busqueda.setNumeroEjes(Integer.parseInt(txtNumeroEjes.getText()));
        }
        busqueda.setNumeroLicencia(txtNumeroLicencia.getText());
        busqueda.setNumeroMotor(txtNumeroMotor.getText());
        busqueda.setPlaca(txtPlaca.getText());
        //Servicio
        if (textAutoAcompleterServicio.getItemSelected() != null && !txtServicio.getText().isEmpty()) {
            Datos datosServicio = ((Datos) textAutoAcompleterServicio.findItem(txtServicio.getText()));
            if (!datosServicio.getNombre().isEmpty() && datosServicio.getId() > 0) {
                busqueda.setServicio(datosServicio.getId());
            }
        } else {
            busqueda.setServicio(0);
        }
        if (textAutoAcompleterTipo.getItemSelected() != null && !txtTipo.getText().isEmpty()) {
            Datos datosTipo = ((Datos) textAutoAcompleterTipo.findItem(txtTipo.getText()));
            if (!datosTipo.getNombre().isEmpty() && datosTipo.getId() > 0) {
                busqueda.setTipo(datosTipo.getId());
            }
        } else {
            busqueda.setTipo(0);
        }
        busqueda.setVin(txtVin.getText());

        if (!txtNumeroEjes.getText().isEmpty()) {
            busqueda.setNumeroEjes(Integer.parseInt(txtNumeroEjes.getText()));
        }

        busqueda.setNumeroLicencia(txtNumeroLicencia.getText());

        if (!txtIdPropietario.getText().isEmpty()) {
            busqueda.setIdPropietario(Long.parseLong(txtIdPropietario.getText()));
        }

        busqueda.setNumeroMotor(txtNumeroMotor.getText());

        busqueda.setPlaca(txtPlaca.getText());
        if (cmbEstado.getSelectedItem() == null) {
            busqueda.setEstado("");
        } else {
            busqueda.setEstado(cmbEstado.getSelectedItem().toString());
        }

        StringBuilder sb = new StringBuilder();
        if (validarCampos(busqueda.getApellido(), busqueda.getNombre())) { 
            sb.append("select hp.* from vehiculos v INNER join hoja_pruebas hp ON v.CAR=hp.Vehiculo_for inner join propietarios p on v.`CAROWNER` = p.`CAROWNER` where v.`CAR` = v.`CAR` ");
        } else {
            sb.append("select hp.* from vehiculos v INNER join hoja_pruebas hp ON v.CAR=hp.Vehiculo_for where v.`CAR` = v.`CAR` ");
        }
        if (validarCampos(busqueda.getNombre())) {
            sb.append("and p.`Nombres` like '%").append(busqueda.getNombre()).append("%' ");
        }

        if (validarCampos(busqueda.getApellido())) {
            sb.append("and p.`Apellidos` like '%").append(busqueda.getApellido()).append("%' ");
        }
        if ((busqueda.getNumeroEjes()) > 0) {
            sb.append("and v.`Numero_ejes` like '%").append(busqueda.getNumeroEjes()).append("%' ");
        }
        if (busqueda.getCilindraje() > 0) {
            sb.append("and v.`Cinlindraje`").append(busqueda.getCmbcilindraje()).append(busqueda.getCilindraje()).append(" ");
        }
        if (busqueda.getModelo() > 0) {
            sb.append("and v.`Modelo` ").append(busqueda.getCmbModelo()).append(busqueda.getModelo()).append(" ");
        }

        if (validarCampos(busqueda.getNumeroLicencia())) {
            sb.append("and v.`Numero_licencia` like '%").append(busqueda.getNumeroLicencia()).append("%' ");//SART-21 se modifica ya que se debe buscar por el numero de licencia de el vehiculo y no del propietario
        }
        if (validarCampos(busqueda.getPlaca())) {
            sb.append("and v.`CARPLATE` like '%").append(busqueda.getPlaca()).append("%' ");
        }
        if (validarCampos(busqueda.getEstado()) && !busqueda.getEstado().equals(" ")) {

            sb.append("and hp.`estado` = '").append(busqueda.getEstado()).append("' ");
        }
        if (dteFechaFinal.getDate() != null || dteFechaInicial.getDate() != null) {
            if (dteFechaFinal.getDate() == null || dteFechaInicial.getDate() == null) {
                Mensajes.mensajeAdvertencia("Debe seleccionar las dos fechas");
            }
            SimpleDateFormat formateador = new SimpleDateFormat("yyyy-MM-dd");
            sb.append("and hp.Fecha_ingreso_vehiculo between '").append(formateador.format(dteFechaInicial.getDate())).append("' and '").append(formateador.format(dteFechaFinal.getDate())).append("' ");
        }
        if (validarCampos(busqueda.getNumeroMotor())) {
            sb.append("and v.`Numero_motor` like '%").append(busqueda.getNumeroMotor()).append("%' ");
        }
        if (busqueda.getIdPropietario() > 0) {
            sb.append("and p.`CAROWNER` like '%").append(busqueda.getIdPropietario()).append("%' ");
        }
        if (busqueda.getServicio() > 0) {
            sb.append(String.format("and v.`SERVICE` = %d ", busqueda.getServicio()));
        }

        if (busqueda.getLinea() > 0) {
            sb.append(String.format("and v.`CARLINE` = %d ", busqueda.getLinea()));
        }
        if (busqueda.getClase() > 0) {
            sb.append(String.format("and v.`CLASS` = %d ", busqueda.getClase()));
        }
        if (busqueda.getMarca() > 0) {
            sb.append(String.format("and v.`CARMARK` = %d ", busqueda.getMarca()));
        }
        if (busqueda.getTipo() > 0) {
            sb.append(String.format("and v.`CARTYPE` = %d ", busqueda.getTipo()));
        }
        System.out.println(sb);
        byFecha.cargarHojas(sb.toString());
//        HojaPruebasJpaController controller = new HojaPruebasJpaController();
//        List<HojaPruebas> h = controller.BuscarCriterios(sb.toString());
//        for (HojaPruebas hojaPruebas : h) {
//            System.out.println(hojaPruebas);
//        }
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void lbl_estadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_estadoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_estadoMouseClicked

    public boolean validarCampos(String... arg) {
        for (String string : arg) {
            if (string != null && !string.isEmpty()) {
                return true;
            }
        }
        return false;
    }

    public void cargarLista() {
        textAutoAcompleterTipo = new TextAutoCompleter(txtTipo);
        textAutoAcompleterTipo.setMode(0);
        TipoVehiculoJpaController jpaControllerTipo = new TipoVehiculoJpaController();
        ClaseVehiculo clase_vehiculo = new ClaseVehiculo();
        List<TipoVehiculo> listTipo = jpaControllerTipo.findAll();
        List<Datos> datosTipo = new ArrayList<Datos>();
        for (TipoVehiculo v : listTipo) {
            datosTipo.add(new Datos(v.getId(), v.getNombre()));
        }
        textAutoAcompleterTipo.addItems(datosTipo.toArray());

        textAutoAcompleterMarca = new TextAutoCompleter(txtMarca);
        textAutoAcompleterMarca.setMode(0);
        MarcaJpaController jpaControllerMarca = new MarcaJpaController();
        Marca marca = new Marca();
        List<Datos> datosMarca = new ArrayList<Datos>();
        List<Marca> listMarca = jpaControllerMarca.findAll();
        for (Marca M : listMarca) {
            datosMarca.add(new Datos(M.getId(), M.getNombre()));
        }
        textAutoAcompleterMarca.addItems(datosMarca.toArray());

        textAutoAcompletercClase = new TextAutoCompleter(txtClase);
        textAutoAcompletercClase.setMode(0);
        ClaseVehiculoJpaController jpaControllerClase = new ClaseVehiculoJpaController();
        List<Datos> datosClase = new ArrayList<Datos>();
        List<ClaseVehiculo> listClaseVehiculo = jpaControllerClase.findAll();
        for (ClaseVehiculo C : listClaseVehiculo) {
            datosClase.add(new Datos(C.getId(), C.getNombre()));
        }
        textAutoAcompletercClase.addItems(datosClase.toArray());

        textAutoAcompleterServicio = new TextAutoCompleter(txtServicio);
        textAutoAcompleterServicio.setMode(0);
        ServicioJpaController jpaControllerServicio = new ServicioJpaController();
        Servicio servicio = new Servicio();
        List<Datos> datosServicio = new ArrayList<Datos>();
        List<Servicio> listClaseServicio = jpaControllerServicio.findAll();
        for (Servicio s : listClaseServicio) {
            datosServicio.add(new Datos(s.getId(), s.getNombre()));
        }
        textAutoAcompleterServicio.addItems(datosServicio.toArray());

        textAutoAcompleterLinea = new TextAutoCompleter(txtLinea);
        textAutoAcompleterLinea.setMode(0);
        LineaVehiculoJpaController jpaControllerLinea = new LineaVehiculoJpaController();
        LineaVehiculo lineavehiculo = new LineaVehiculo();
        List<Datos> datosLineae = new ArrayList<Datos>();
        List<LineaVehiculo> listClaseLinea = jpaControllerLinea.findLineaVehiculoEntities();
        for (LineaVehiculo l : listClaseLinea) {
            datosLineae.add(new Datos(l.getId(), l.getNombre()));
        }
        textAutoAcompleterLinea.addItems(datosLineae.toArray());
    }

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CriteriosBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CriteriosBusqueda().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCilindraje;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbModelo;
    private org.jdesktop.swingx.JXDatePicker dteFechaFinal;
    private org.jdesktop.swingx.JXDatePicker dteFechaInicial;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_estado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCilindraje;
    private javax.swing.JTextField txtClase;
    private javax.swing.JTextField txtIdPropietario;
    private javax.swing.JTextField txtLinea;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtNumeroEjes;
    private javax.swing.JTextField txtNumeroLicencia;
    private javax.swing.JTextField txtNumeroMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtServicio;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtVin;
    // End of variables declaration//GEN-END:variables
}
