 /*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.consolaentrada.views;

import java.awt.AWTException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import java.awt.Component;
import java.awt.Robot;
import java.awt.Window;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.Timer;

/**
 *
 * @author GerenciaDesarrollo
 */
public class FrmComentario extends javax.swing.JDialog {

    java.awt.Frame frame;

    private String motivoAnulacion;
    private String funcion;
    private Timer timer = null;
    public static String obsNulidad;

    //DIRECCIÓN IP DEL SERVIDOR = 186.112.176.34
    //---
    FrmComentario(Window owner, ModalityType modalityType, String motivoAnulacion) {
        super(owner, modalityType);
        initComponents();
        Dimension d = new java.awt.Dimension(688, 172);
        setSize(d);
        System.out.println("c");
        setTitle("Motivo de la Anulacion..¡");
        this.requestFocusInWindow();

        setResizable(false);
        if (motivoAnulacion != null) {
            this.txtComent.setText(motivoAnulacion);
        } else {
            this.motivoAnulacion = "";
        }       
        this.funcion = funcion;
        this.txtComent.requestFocus();
        timer = new Timer(575, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    Robot ro = new Robot();
                    ro.keyPress(KeyEvent.VK_TAB);
                    System.out.printf("Robot ya hizo tab");
                    timer.stop();
                } catch (AWTException ex) {
                }
            }
        });

        timer.start();
    }

    ////////////////////////////////////////////PARA NO PERDER LA REFERENCIA DEL OBJETO/////////
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtObservacion = new javax.swing.JScrollPane();
        txtComent = new javax.swing.JTextArea();
        lblAdventencias = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.POPUP);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Especifique la Nulidad ");

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\opt\\Consola Entrada\\src\\main\\resources\\com\\soltelec\\consolaentrada\\images\\save_24.png")); // NOI18N
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtObservacion.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N

        txtComent.setColumns(20);
        txtComent.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtComent.setLineWrap(true);
        txtComent.setRows(5);
        txtComent.setTabSize(0);
        txtComent.setWrapStyleWord(true);
        txtComent.setPreferredSize(new java.awt.Dimension(200, 89));
        txtComent.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtComentFocusGained(evt);
            }
        });
        txtComent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtComentKeyPressed(evt);
            }
        });
        txtObservacion.setViewportView(txtComent);

        lblAdventencias.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblAdventencias.setForeground(new java.awt.Color(204, 0, 0));
        lblAdventencias.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAdventencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtObservacion)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblAdventencias, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setBounds(0, 0, 537, 198);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (this.txtComent.getText().length() <= 3) {
            this.lblAdventencias.setText("Disculpe NO SE ME HA ESPECIFICADO EL MOTIVO DE LA NULIDAD");
        } else {
            FrmComentario.obsNulidad = this.txtComent.getText();
            this.dispose();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtComentKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtComentKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtComentKeyPressed

    private void txtComentFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtComentFocusGained
        this.lblAdventencias.setText(" ");
    }//GEN-LAST:event_txtComentFocusGained
    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /////////////////////////////////MÉTODOS SOBRE LA FUNCIONALIDAD //////////////////////////////
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmComentario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    Robot ro = new Robot();
                    ro.keyPress(KeyEvent.VK_TAB);
                } catch (AWTException ex) {
                    Logger.getLogger(FrmComentario.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAdventencias;
    private javax.swing.JTextArea txtComent;
    private javax.swing.JScrollPane txtObservacion;
    // End of variables declaration//GEN-END:variables
    private int returnStatus = 0;
}
