/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.soltelec.consolaentrada.views;

import com.soltelec.consolaentrada.custom.ModeloTablaHojas;
import com.soltelec.consolaentrada.models.controllers.HojaPruebasJpaController;
import com.soltelec.consolaentrada.models.controllers.ReinspeccionJpaController;
import com.soltelec.consolaentrada.models.entities.HojaPruebas;
import com.soltelec.consolaentrada.models.entities.Reinspeccion;
import com.soltelec.consolaentrada.reporte.LlamarReporte;
import com.soltelec.consolaentrada.utilities.Mensajes;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;

/**
 * @author Dany
 */
public class PanelReinspecciones extends javax.swing.JPanel {

    private final ModeloTablaHojas modeloTablaHojas;
    private LlamarReporte llamarReporte;
    private Reinspeccion reinspecionActual;
    
    /**
     * Creates new form PanelReinspeccion
     */
    public PanelReinspecciones() {
        modeloTablaHojas = new ModeloTablaHojas();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPlaca = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHojaPruebas = new javax.swing.JTable();
        btnBuscar = new javax.swing.JButton();
        lblPlaca1 = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        lblPlaca2 = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblPlaca4 = new javax.swing.JLabel();
        lblAprobada = new javax.swing.JLabel();
        lblPlaca5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        lblPlaca.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlaca.setText("Placa");

        txtPlaca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPlaca.setPreferredSize(new java.awt.Dimension(150, 40));
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        tblHojaPruebas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHojaPruebas.setModel(modeloTablaHojas);
        tblHojaPruebas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHojaPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHojaPruebasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHojaPruebas);

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setPreferredSize(new java.awt.Dimension(140, 40));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblPlaca1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlaca1.setText("ID");

        lblId.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblId.setText("00000");
        lblId.setPreferredSize(new java.awt.Dimension(80, 29));

        lblPlaca2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlaca2.setText("Fecha");

        lblFecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblFecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFecha.setText("00/00/0000");
        lblFecha.setPreferredSize(new java.awt.Dimension(132, 29));

        lblPlaca4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlaca4.setText("Aprobada");

        lblAprobada.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAprobada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAprobada.setText("NO");
        lblAprobada.setPreferredSize(new java.awt.Dimension(45, 29));

        lblPlaca5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblPlaca5.setText("Comentario");

        txtComentario.setEditable(false);
        txtComentario.setColumns(20);
        txtComentario.setRows(5);
        jScrollPane2.setViewportView(txtComentario);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPlaca5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane2))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lblPlaca1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblPlaca2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblPlaca4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblAprobada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPlaca)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaca)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPlaca1)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPlaca2)
                        .addComponent(lblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPlaca4)
                        .addComponent(lblAprobada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlaca5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/solt.png"))); // NOI18N

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setPreferredSize(new java.awt.Dimension(140, 40));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnPdf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPdf.setText("PDF");
        btnPdf.setPreferredSize(new java.awt.Dimension(140, 40));
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(140, 40));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarDatos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        if (reinspecionActual == null) {
            Mensajes.mensajeAdvertencia("Que Pena ,No Encuentro Ninguna Reinspección para Imprimir");
            return;
        }        
        llamarReporte = new LlamarReporte();        
        try {
            llamarReporte.setImprimirPdf(false);
            llamarReporte.cargarReporteReinspeccion(reinspecionActual);
        } catch (Exception ex) {
            Mensajes.mostrarExcepcion(ex);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void tblHojaPruebasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHojaPruebasMouseClicked
        Integer idHojaPruebas = modeloTablaHojas.getListaHojaPruebas().get(tblHojaPruebas.getSelectedRow()).getId();
        reinspecionActual = new ReinspeccionJpaController().findReinspeccionByHoja(idHojaPruebas);
        llenarCamposReinspeccion(reinspecionActual);
    }//GEN-LAST:event_tblHojaPruebasMouseClicked

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        llenarCamposReinspeccion(null);
        txtPlaca.setText("");
        modeloTablaHojas.setListaHojaPruebas(new ArrayList<HojaPruebas>());
        ViewManager.getInstance().showPrincipal();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        buscarDatos();
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        if (reinspecionActual == null) {
            Mensajes.mensajeAdvertencia("No hay reinspección para imprimir");
            return;
        }
        
        llamarReporte = new LlamarReporte();
        
        try {
            llamarReporte.setImprimirPdf(true);
            llamarReporte.cargarReporteReinspeccion(reinspecionActual);
        } catch (Exception ex) {
            Mensajes.mostrarExcepcion(ex);
        }
    }//GEN-LAST:event_btnPdfActionPerformed

    public static void main(String[] args) {
        ViewManager.getInstance().showReinspeccion();
    }

    private void buscarDatos() {
        modeloTablaHojas.setListaHojaPruebas(new ArrayList<HojaPruebas>());
        
        if (txtPlaca.getText().equals("")) {
            Mensajes.mensajeAdvertencia("El campo de la placa no debe estar vacio");
            return;
        }
        
        List<HojaPruebas> hojasPruebas = new HojaPruebasJpaController().findHojaPruebasWithReinspeccionByPlaca(txtPlaca.getText());
        
        if (hojasPruebas == null || hojasPruebas.isEmpty()) {
            Mensajes.mensajeAdvertencia("La placa " + txtPlaca.getText() + " no se encuentra registrada o no tiene reinspecciones");
            txtPlaca.setText("");
            llenarCamposReinspeccion(null);
            return;
        }
        
        modeloTablaHojas.setListaHojaPruebas(hojasPruebas);
        
        if (!modeloTablaHojas.getListaHojaPruebas().isEmpty()) {
            tblHojaPruebas.setRowSelectionInterval(0, 0);
            reinspecionActual = new ReinspeccionJpaController().findReinspeccionByHoja(modeloTablaHojas.getListaHojaPruebas().get(0).getId());
            llenarCamposReinspeccion(reinspecionActual);
        }  
    }
    
    private void llenarCamposReinspeccion(Reinspeccion reinspeccion) {
        if (reinspeccion == null) {
            lblId.setText("00000");
            lblFecha.setText("00/00/0000");
            lblAprobada.setText("NO");
            txtComentario.setText("");
        } else {
            lblId.setText(String.valueOf(reinspeccion.getId()));
            lblFecha.setText(new SimpleDateFormat("dd/MM/yyyy").format(reinspeccion.getFechaSiguiente()));
            lblAprobada.setText(reinspeccion.getAprobada().equals("Y") ? "SI": "NO");
            txtComentario.setText(reinspeccion.getComentario());
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblAprobada;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblPlaca1;
    private javax.swing.JLabel lblPlaca2;
    private javax.swing.JLabel lblPlaca4;
    private javax.swing.JLabel lblPlaca5;
    private javax.swing.JTable tblHojaPruebas;
    private javax.swing.JTextArea txtComentario;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
