/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.soltelec.consolaentrada.views;

import javax.swing.*;

/**
 *
 * @author Dany
 */
public class PanelPrincipal1 extends javax.swing.JPanel {
    
    /**
     * Creates new form PanelHojaImprimirv2
     */
    public PanelPrincipal1() {
        initComponents();
    }

    public JButton getBtnRevisiones() {
        return btnRevisiones;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        btnRevisiones = new javax.swing.JButton();
        btnReinspecciones = new javax.swing.JButton();
        btnReportesPlaca = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnReportesFecha = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(800, 600));

        btnRevisiones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRevisiones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/RevisionesM.png"))); // NOI18N
        btnRevisiones.setText("REVISIONES");
        btnRevisiones.setBorder(null);
        btnRevisiones.setBorderPainted(false);
        btnRevisiones.setContentAreaFilled(false);
        btnRevisiones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRevisiones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRevisiones.setIconTextGap(-2);
        btnRevisiones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/RevisionesP.png"))); // NOI18N
        btnRevisiones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/RevisionesG.png"))); // NOI18N
        btnRevisiones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnRevisiones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRevisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevisionesActionPerformed(evt);
            }
        });

        btnReinspecciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReinspecciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/ReinspeccionM.png"))); // NOI18N
        btnReinspecciones.setText("REINSPECCIONES");
        btnReinspecciones.setBorder(null);
        btnReinspecciones.setBorderPainted(false);
        btnReinspecciones.setContentAreaFilled(false);
        btnReinspecciones.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReinspecciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReinspecciones.setIconTextGap(-2);
        btnReinspecciones.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/ReinspeccionP.png"))); // NOI18N
        btnReinspecciones.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/ReinspeccionG.png"))); // NOI18N
        btnReinspecciones.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReinspecciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReinspecciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReinspeccionesActionPerformed(evt);
            }
        });

        btnReportesPlaca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReportesPlaca.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/PlacaM.png"))); // NOI18N
        btnReportesPlaca.setText("REPORTES - PLACA");
        btnReportesPlaca.setBorder(null);
        btnReportesPlaca.setBorderPainted(false);
        btnReportesPlaca.setContentAreaFilled(false);
        btnReportesPlaca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportesPlaca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportesPlaca.setIconTextGap(-2);
        btnReportesPlaca.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/PlacaP.png"))); // NOI18N
        btnReportesPlaca.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/PlacaG.png"))); // NOI18N
        btnReportesPlaca.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportesPlaca.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportesPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesPlacaActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/SalirM.png"))); // NOI18N
        btnSalir.setText("SALIR");
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalir.setIconTextGap(-2);
        btnSalir.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/SalirP.png"))); // NOI18N
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/SalirG.png"))); // NOI18N
        btnSalir.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnReportesFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReportesFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/FechaM.png"))); // NOI18N
        btnReportesFecha.setText("REPORTES - FECHA");
        btnReportesFecha.setBorder(null);
        btnReportesFecha.setBorderPainted(false);
        btnReportesFecha.setContentAreaFilled(false);
        btnReportesFecha.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReportesFecha.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReportesFecha.setIconTextGap(-2);
        btnReportesFecha.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/FechaP.png"))); // NOI18N
        btnReportesFecha.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/FechaG.png"))); // NOI18N
        btnReportesFecha.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnReportesFecha.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReportesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalir)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRevisiones)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportesFecha)
                        .addGap(18, 18, 18)
                        .addComponent(btnReportesPlaca)
                        .addGap(18, 18, 18)
                        .addComponent(btnReinspecciones)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnReportesFecha)
                    .addComponent(btnRevisiones)
                    .addComponent(btnReportesPlaca)
                    .addComponent(btnReinspecciones))
                .addGap(18, 18, 18)
                .addComponent(btnSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/soltelec/consolaentrada/images/SoltelecIcon.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRevisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRevisionesActionPerformed
        ViewManager.getInstance().showRevisiones();
    }//GEN-LAST:event_btnRevisionesActionPerformed

    private void btnReportesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesFechaActionPerformed
        ViewManager.getInstance().showImpresionesByFecha();
    }//GEN-LAST:event_btnReportesFechaActionPerformed

    private void btnReportesPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesPlacaActionPerformed
        ViewManager.getInstance().showImpresionesByPlaca();
    }//GEN-LAST:event_btnReportesPlacaActionPerformed

    private void btnReinspeccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReinspeccionesActionPerformed
        ViewManager.getInstance().showReinspeccion();
    }//GEN-LAST:event_btnReinspeccionesActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReinspecciones;
    private javax.swing.JButton btnReportesFecha;
    private javax.swing.JButton btnReportesPlaca;
    private javax.swing.JButton btnRevisiones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JPanel pnlPrincipal;
    // End of variables declaration//GEN-END:variables
}
