/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.consolaentrada.views;

import com.soltelec.consolaentrada.custom.ModeloTablaImpresionFecha;
import com.soltelec.consolaentrada.custom.ModeloTablaPruebas;
import com.soltelec.consolaentrada.models.controllers.HojaPruebasJpaController;
import com.soltelec.consolaentrada.models.controllers.UsuarioJpaController;
import com.soltelec.consolaentrada.models.entities.HojaPruebas;
import com.soltelec.consolaentrada.models.entities.Prueba;
import com.soltelec.consolaentrada.reporte.ImpresionReporte;
import com.soltelec.consolaentrada.utilities.GenericExportExcel;
import com.soltelec.consolaentrada.utilities.Mensajes;
import org.jdesktop.swingx.JXDatePicker;
import com.soltelec.consolaentrada.models.controllers.CdaJpaController;
import com.soltelec.consolaentrada.models.entities.Cda;
import com.soltelec.consolaentrada.models.entities.RespuestaDTO;
import com.soltelec.consolaentrada.sicov.ci2.ClienteCi2;
import com.soltelec.consolaentrada.sicov.ci2.Pin;

import javax.swing.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;

/**
 *
 * @author GerenciaDesarrollo
 */
public class PanelImpresionByFecha extends javax.swing.JPanel {

    private final ModeloTablaImpresionFecha modeloTablaImpresionFecha;
    private final ModeloTablaPruebas modeloTablaPruebas;
    private ImpresionReporte impresionReporte;
    private Integer idHojaPrueba = -1;
    private HojaPruebas ctxHP = null;
    

    /**
     * Creates new form PanelImpresionByFecha
     */
    public PanelImpresionByFecha() {
        modeloTablaImpresionFecha = new ModeloTablaImpresionFecha();
        modeloTablaPruebas = new ModeloTablaPruebas();
        initComponents();
        modeloTablaImpresionFecha.setListaHojaPruebas(null);        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dteFechaInicial = new JXDatePicker(new Date(),new Locale("es"));
        dteFechaInicial.setFormats(new String[]{"dd/MM/yyyy"});
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dteFechaFinal = new JXDatePicker(new Date(),new Locale("es"));
        dteFechaInicial.setFormats(new String[]{"dd/MM/yyyy"});
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHojaPruebas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPruebas = new javax.swing.JTable();
        CmbBusqueda = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        btnBuscar1 = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        btnImprimir1 = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jLabel5.setText("jLabel5");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("IMPRESIÓN POR FECHA");

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        dteFechaInicial.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dteFechaInicial.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        dteFechaInicial.setPreferredSize(new java.awt.Dimension(180, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Fecha Inicial");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Fecha Final");

        dteFechaFinal.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        dteFechaFinal.setFormats(new SimpleDateFormat("dd/MM/yyyy"));
        dteFechaFinal.setPreferredSize(new java.awt.Dimension(180, 40));

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblHojaPruebas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHojaPruebas.setModel(modeloTablaImpresionFecha);
        tblHojaPruebas.setName("Hojas de Pruebas"); // NOI18N
        tblHojaPruebas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHojaPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHojaPruebasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHojaPruebas);

        tblPruebas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPruebas.setModel(modeloTablaPruebas);
        tblPruebas.setColumnSelectionAllowed(true);
        tblPruebas.setFocusable(false);
        tblPruebas.setRowSelectionAllowed(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, btnAtras, org.jdesktop.beansbinding.ELProperty.create("${foreground.green}"), tblPruebas, org.jdesktop.beansbinding.BeanProperty.create("selectedElement"));
        bindingGroup.addBinding(binding);

        tblPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPruebasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblPruebasMouseEntered(evt);
            }
        });
        tblPruebas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblPruebasMouseMoved(evt);
            }
        });
        tblPruebas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tblPruebasFocusGained(evt);
            }
        });
        jScrollPane2.setViewportView(tblPruebas);
        tblPruebas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        CmbBusqueda.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "todas", "Registrada", "preventiva", "RTM", "INICIADO", "Env1FUR" }));

        jLabel4.setText("Buscar por:");

        btnBuscar1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar1.setText("Filtros");
        btnBuscar1.setPreferredSize(new java.awt.Dimension(120, 40));
        btnBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dteFechaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(dteFechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CmbBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))
        );

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setPreferredSize(new java.awt.Dimension(140, 40));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnPdf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPdf.setText("PDF");
        btnPdf.setPreferredSize(new java.awt.Dimension(140, 40));
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(140, 40));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnExcel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnExcel.setText("Excel");
        btnExcel.setPreferredSize(new java.awt.Dimension(140, 40));
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });

        btnImprimir1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnImprimir1.setText("Iniciar Pin");
        btnImprimir1.setPreferredSize(new java.awt.Dimension(140, 40));
        btnImprimir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimir1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 1086, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(71, 71, 71)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnImprimir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        impresionReporte = new ImpresionReporte();
        impresionReporte.setNumeroHojaPrueba(idHojaPrueba);
        impresionReporte.setImprimirPdf(false);
        impresionReporte.preguntarConsecutivos(this.ctxHP);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        impresionReporte = new ImpresionReporte();
        impresionReporte.setNumeroHojaPrueba(idHojaPrueba);
        impresionReporte.setImprimirPdf(true);
         UsuarioJpaController usrCon = new UsuarioJpaController();
        EntityManager em = usrCon.getEntityManager();
        em.getTransaction().begin();
        em.flush();
        em.getTransaction().commit();
        impresionReporte.preguntarConsecutivos(this.ctxHP);
    }//GEN-LAST:event_btnPdfActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        idHojaPrueba = -1;
        modeloTablaImpresionFecha.setListaHojaPruebas(new ArrayList<HojaPruebas>());
        modeloTablaPruebas.setListPruebas(new ArrayList<Prueba>());
        ViewManager.getInstance().showPrincipal();
    }//GEN-LAST:event_btnAtrasActionPerformed

    public void cargarHojas(String consulta) {
        modeloTablaImpresionFecha.setListaHojaPruebas(new HojaPruebasJpaController().BuscarCriterios(consulta));
    }

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        if (dteFechaFinal.getDate() == null || dteFechaInicial.getDate() == null) {
            Mensajes.mensajeAdvertencia("Disculpe, no ha seleccionado al menos una fecha de Busqueda");
        }

        idHojaPrueba = -1;
        String Seleccion = (String) CmbBusqueda.getSelectedItem();

        switch (Seleccion) {
             case "Registrada":
                modeloTablaImpresionFecha.setListaHojaPruebas(new HojaPruebasJpaController().findHojasEdoEnv1FUR(dteFechaInicial.getDate(), dteFechaFinal.getDate(), "Registrada"));
                break;
            case "preventiva":
                modeloTablaImpresionFecha.setListaHojaPruebas(new HojaPruebasJpaController().findHojaPreventivaPruebasByFecha(dteFechaInicial.getDate(), dteFechaFinal.getDate()));
                break;
            case "RTM":
                modeloTablaImpresionFecha.setListaHojaPruebas(new HojaPruebasJpaController().findHojaPruebaByFecha(dteFechaInicial.getDate(), dteFechaFinal.getDate()));
                break;
            case "todas":
                modeloTablaImpresionFecha.setListaHojaPruebas(new HojaPruebasJpaController().findHojaPruebasByFecha(dteFechaInicial.getDate(), dteFechaFinal.getDate()));
                break;
            case "Env1FUR":
                modeloTablaImpresionFecha.setListaHojaPruebas(new HojaPruebasJpaController().findHojasEdoEnv1FUR(dteFechaInicial.getDate(), dteFechaFinal.getDate(), "Env1FUR"));
                break;
            case "INICIADO":
                modeloTablaImpresionFecha.setListaHojaPruebas(new HojaPruebasJpaController().findHojasEdoEnv1FUR(dteFechaInicial.getDate(), dteFechaFinal.getDate(), "INICIADO"));
                break;
        }

        if (!modeloTablaImpresionFecha.getListaHojaPruebas().isEmpty()) {
            this.ctxHP = modeloTablaImpresionFecha.getListaHojaPruebas().get(0);
            tblHojaPruebas.setRowSelectionInterval(0, 0);
            ModeloTablaPruebas.cntTest=0;
            ModeloTablaPruebas.cntColum=0;
            modeloTablaPruebas.setListPruebas(this.ctxHP.getListPruebas());
            idHojaPrueba = this.ctxHP.getId();
        } else {
            Mensajes.mensajeAdvertencia("No hay datos registrados para estas fechas");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblHojaPruebasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHojaPruebasMouseClicked
        HojaPruebas hojaPruebas = modeloTablaImpresionFecha.getListaHojaPruebas().get(tblHojaPruebas.getSelectedRow());
        HojaPruebasJpaController controHP = new HojaPruebasJpaController();;
        ctxHP = controHP.find(hojaPruebas.getId());
        ModeloTablaPruebas.cntTest=0;
        ModeloTablaPruebas.cntColum=0;
        modeloTablaPruebas.setListPruebas(ctxHP.getListPruebas());      
        idHojaPrueba = ctxHP.getId();
    }//GEN-LAST:event_tblHojaPruebasMouseClicked

    //Metodo para generar el reporte en excel partiedo de los datos que se encuentren
    //en la tabla de hoja de pruebas.
    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        if (ViewManager.aplicYellow == true) {
            EntityManager em;
            int cntClv = 1;
            while (true) {
                FrmPassword frmP = new FrmPassword(null, JDialog.ModalityType.MODELESS);
                frmP.setModal(true);
                frmP.setLocationRelativeTo(null);
                frmP.setVisible(true);
                UsuarioJpaController usrCon = new UsuarioJpaController();
                em = usrCon.getEntityManager();
                Boolean paso = UsuarioJpaController.findUsuariosByAdmYellow(FrmPassword.parametro, em);
                if (paso == true) {
                    FrmPassword.desistir = false;
                    break;
                } else {
                    if (cntClv == 2) {
                        FrmPassword.desistir = true;
                        FrmPassword.msgApp = "";
                        break;
                    }
                    FrmPassword.msgApp = "Intente de Nvo. Clave no Encontrada";
                    cntClv++;
                }
            }
            if(FrmPassword.desistir == false){
                 HojaPruebasJpaController controller = new HojaPruebasJpaController();
                 if(ctxHP.getAnulado().equalsIgnoreCase("A")){
                    this.ctxHP.setAnulado("N");     
                 }else{
                    this.ctxHP.setAnulado("A"); 
                 }                
                try {
                    controller.editSingle(ctxHP);
                    Mensajes.mensajeCorrecto("Tomado HP para Exportacion Excel");                    
                } catch (Exception ex) {
                    Logger.getLogger(PanelImpresionByFecha.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            if (modeloTablaImpresionFecha.getListaHojaPruebas().isEmpty()) {
                Mensajes.mensajeAdvertencia("No hay datos para exportar");
                return;
            }
            GenericExportExcel exportExcel = new GenericExportExcel();
            exportExcel.exportExcel(tblHojaPruebas);
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private void btnBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscar1ActionPerformed
        CriteriosBusqueda busqueda = new CriteriosBusqueda(this);
        busqueda.setVisible(true);
    }//GEN-LAST:event_btnBuscar1ActionPerformed

    private void tblPruebasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPruebasMouseEntered
        
    }//GEN-LAST:event_tblPruebasMouseEntered

    private void tblPruebasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPruebasMouseClicked
      
    }//GEN-LAST:event_tblPruebasMouseClicked

    private void tblPruebasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tblPruebasFocusGained
       
    }//GEN-LAST:event_tblPruebasFocusGained

    private void tblPruebasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPruebasMouseMoved
      JTable jt = (JTable) evt.getSource();
      ModeloTablaPruebas.jTable=jt;
    }//GEN-LAST:event_tblPruebasMouseMoved

    private void btnImprimir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimir1ActionPerformed
        Cda ctxCDA;
        HojaPruebas ctxHojaPrueba;
        HojaPruebasJpaController controller = new HojaPruebasJpaController();
        CdaJpaController cdaControler = cdaControler = new CdaJpaController();
        ctxCDA = cdaControler.find(1);
        ctxHojaPrueba = controller.find(this.ctxHP.getId());
        
        if (ctxCDA.getProveedorSicov().equals("CI2")) {
            try {
                Pin pin = new Pin();               
                pin.setClave(ctxCDA.getPasswordSicov());
                pin.setP_placa(ctxHojaPrueba.getVehiculo().getPlaca());
                pin.setUsuario(ctxCDA.getUsuarioSicov());
                ClienteCi2 clienteCi2 = new ClienteCi2(ctxCDA.getUrlServicioSicov());
                RespuestaDTO respuestaDTO = clienteCi2.consultarPinPlaca(pin);
                if (respuestaDTO == null) {
                    Mensajes.mensajeAdvertencia("Disculpe, No he Tenido COMUNICACION con el Servidor CI2 en este momento ..! \n Intente dentro de un Minuto si el problema persiste COMUNIQUESE con la Mesa de Ayuda");
                    Mensajes.mensajeAdvertencia("Por Favor, se RECOMIENDA NO continuar con el REGISTRO DEL VEHICULO, PARA NO GENERAR INCONSISTENCIAS ..!");                   
                    return;
                }
                if (respuestaDTO.getCodigoRespuesta().equalsIgnoreCase("2006")) {
                    String temp = respuestaDTO.getMensajeRespuesta().split("@")[1];
                    respuestaDTO.setMensajeRespuesta(temp.replace("|TD", ""));                    
                    String ctxPing = respuestaDTO.getMensajeRespuesta();
                    System.out.println(ctxPing);
                    ctxHojaPrueba.setPin(ctxPing);
                   ctxHojaPrueba.setEstadoSICOV("Iniciado");
                   controller.editCasoAddPin(ctxHojaPrueba);
                } else {
                    Mensajes.mensajeAdvertencia("Disculpe, No he podido ASOCIAR el Pin debido a :" + respuestaDTO.getMensajeRespuesta());
                    return;
                }
                pin.setP_pin(respuestaDTO.getMensajeRespuesta());
                pin.setP_tipo_rtm("1");
                respuestaDTO = clienteCi2.utilizarPin(pin);
                if (!respuestaDTO.getCodigoRespuesta().equals("0000")) { //ok
                    Mensajes.mensajeAdvertencia("Disculpe, No he podido iniciar el Pin debido a :" + respuestaDTO.getMensajeRespuesta());
                    return;
                } else {
                    Mensajes.mensajeCorrecto("Pin Iniciado con EXITO ..¡ ");
                }
            } catch (Throwable ne) {
               
            }
                        }//Validacion de Proveedor para la busqueda del Pin      
    }//GEN-LAST:event_btnImprimir1ActionPerformed

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.getContentPane().add(new PanelImpresionByFecha());
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CmbBusqueda;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscar1;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnPdf;
    private org.jdesktop.swingx.JXDatePicker dteFechaFinal;
    private org.jdesktop.swingx.JXDatePicker dteFechaInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblHojaPruebas;
    private javax.swing.JTable tblPruebas;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
