/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelCambiarPassword.java
 *
 * Created on 2/12/2011, 11:45:54 AM
 */

package com.soltelec.consolaentrada.views;

import com.soltelec.consolaentrada.models.controllers.UsuarioJpaController;
import com.soltelec.consolaentrada.models.entities.Usuario;
import com.soltelec.consolaentrada.utilities.Mensajes;

import javax.swing.*;
import java.util.Calendar;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 *
 * @author Usuario
 */
public class PanelCambiarPassword extends javax.swing.JDialog {
    /** A return status code - returned if Cancel button has been pressed */
    public static final int RET_CANCEL = 0;
    /** A return status code - returned if OK button has been pressed */
    public static final int RET_OK = 1;
    private UsuarioJpaController ujc;
    private String nickUsuario;

   

    /** Creates new form DlgChangePassword
     * @param parent
     * @param modal */
    public PanelCambiarPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        initComponents();
        this.setLocationRelativeTo(parent);
        this.setTitle("Cambio de Contrasena");
        this.pswdUno.setText("");
        this.pswdUno.setColumns(15);
        this.pswdConfirm.setText("");
        this.pswdConfirm.setColumns(15);
    }

    /** @return the return status of this dialog - one of RET_OK or RET_CANCEL */
    public int getReturnStatus() {
        return returnStatus;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pswdUno = new javax.swing.JPasswordField();
        pswdConfirm = new javax.swing.JPasswordField();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Nueva Contraseña");

        jLabel2.setText("Confirme Nueva Contraseña");

        pswdUno.setText("jPasswordField1");

        pswdConfirm.setText("jPasswordField2");

        txtArea.setEditable(false);
        txtArea.setColumns(20);
        txtArea.setRows(5);
        txtArea.setText("Su nueva contraseña longitud minima 6,\ndebe contener mayusculas y minusculas,\nno debe contener caracteres seguidos\ndebe incluir letras y numeros.");
        jScrollPane2.setViewportView(txtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(35, 35, 35)
                                .addComponent(pswdUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(pswdConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(116, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, okButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(pswdUno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pswdConfirm, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(okButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        String strPas1 = new String(pswdUno.getPassword());
        String strPasConfirm = new String(pswdConfirm.getPassword());

        
        if(strPas1.equals(strPasConfirm)){               
            if (validarRestricciones(strPasConfirm, this.txtArea)){
            //validar que no sea la misma contrasena anterior
            Usuario usuarioByNick = ujc.getUsuarioByNick(nickUsuario);

            if(usuarioByNick.getContrasena().equals(strPas1)){
               JOptionPane.showMessageDialog(rootPane, "Cambie la contrasena no escriba la misma!!!");
               ujc.getEntityManager().close();     
            } else{
                usuarioByNick.setContrasena(strPas1);
                Calendar c = Calendar.getInstance();
                c.add(Calendar.MONTH, +1);
                usuarioByNick.setFechaValidacion(new java.sql.Date(c.getTimeInMillis()));
                try {
                    ujc.edit(usuarioByNick);
                    doClose(RET_OK);
                } catch (Exception ex) {
                    Mensajes.mostrarExcepcion(ex);
                } finally{
                    ujc.getEntityManager().close();
                }
            }

            }
        } else {
            txtArea.setText("");
            txtArea.setText("Ingrese la misma contrasena\n en los dos campos");
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        ujc.getEntityManager().close();
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                PanelCambiarPassword dialog = new PanelCambiarPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton okButton;
    private javax.swing.JPasswordField pswdConfirm;
    private javax.swing.JPasswordField pswdUno;
    private javax.swing.JTextArea txtArea;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;

    
    /**
     * Valida las restricciones para las contrasenas
     * 1. Restriccion de Longitud
     * 2. Restriccion alfa numerica 
     * 4. Restriccion de caracteres seguidos
     * @param strPasConfirm
     * @param mensaje
     * @return
     */
    private boolean validarRestricciones(String strPasConfirm, JTextArea txtArea) {
        //Expresion regular par identificar que tenga un digito y un numero
        Pattern patron = Pattern.compile("[0-9]+[A-z]+|[A-z]+[0-9]");
        Matcher m = patron.matcher(strPasConfirm);

        if(!m.find()){
            txtArea.setText("La nueva contrasena debe tener"
                    + "Digitos y Letras");
            return false;
        } else if(strPasConfirm.length() < 6){
            txtArea.setText("LONGITUD INCORRECTA");
            return false;
        }else if(contieneCaracteresSeguidos(strPasConfirm)){
            txtArea.setText("CONTIENE CARACTERES CONSECUTIVOS "
                    + " O DOS CARACTERES IGUALES SEGUIDOS");
            return false;
        }
        return true;
    }

    private boolean contieneCaracteresSeguidos(String cadena){
        char[] caracteres = cadena.toCharArray();
        for(int i = 0; i < caracteres.length -1; i++){
            char c = caracteres[i];
            char sigChar = caracteres[i+1];
            int valorAbs = Math.abs( (short)c -(short)sigChar );
            if( valorAbs == 1 || valorAbs == 0){
                return true;
            }
        }
        return false;
    }//end of method contieneCaracteresSeguidos

    public UsuarioJpaController getUjc() {
        return ujc;
    }

    public void setUjc(UsuarioJpaController ujc) {
        this.ujc = ujc;
    }

    public String getNickUsuario() {
        return nickUsuario;
    }

    public void setNickUsuario(String nickUsuario) {
        this.nickUsuario = nickUsuario;
    }
}
