/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.soltelec.consolaentrada.views;

import com.soltelec.consolaentrada.custom.ModeloTablaHojas;
import com.soltelec.consolaentrada.custom.ModeloTablaPruebas;
import com.soltelec.consolaentrada.models.controllers.VehiculoJpaController;
import com.soltelec.consolaentrada.models.controllers.HojaPruebasJpaController;
import com.soltelec.consolaentrada.models.entities.HojaPruebas;
import com.soltelec.consolaentrada.models.entities.Prueba;
import com.soltelec.consolaentrada.models.entities.Vehiculo;
import com.soltelec.consolaentrada.reporte.ImpresionReporte;
import com.soltelec.consolaentrada.utilities.Mensajes;

import javax.swing.*;
import java.util.ArrayList;

/**
 *
 * @author GerenciaDesarrollo
 */
public class PanelImpresionByPlaca extends javax.swing.JPanel {

    private final ModeloTablaHojas modeloHojaPruebas;
    private final ModeloTablaPruebas modeloPruebas;
    private ImpresionReporte impresionReporte;
    private Integer idHojaPrueba = -1;
    private HojaPruebas ctxHP = null;

    /**
     * Creates new form PanelImpresionByPlaca
     */
    public PanelImpresionByPlaca() {
        modeloHojaPruebas = new ModeloTablaHojas(new ArrayList<HojaPruebas>());
        modeloPruebas = new ModeloTablaPruebas(new ArrayList<Prueba>());
        initComponents();
        tblHojaPruebas.setModel(modeloHojaPruebas);
        tblPruebas.setModel(modeloPruebas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHojaPruebas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPruebas = new javax.swing.JTable();
        btnImprimir = new javax.swing.JButton();
        btnPdf = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("IMPRESIÓN POR PLACA");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Placa");

        txtPlaca.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtPlaca.setPreferredSize(new java.awt.Dimension(220, 40));
        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        txtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPlacaKeyTyped(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setPreferredSize(new java.awt.Dimension(120, 40));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        tblHojaPruebas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHojaPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Fecha", "Estado", "Preventiva"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHojaPruebas.setDragEnabled(true);
        tblHojaPruebas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblHojaPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHojaPruebasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHojaPruebas);

        tblPruebas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblPruebas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prueba", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPruebas.setFocusable(false);
        tblPruebas.setRowSelectionAllowed(false);
        tblPruebas.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tblPruebasMouseMoved(evt);
            }
        });
        jScrollPane3.setViewportView(tblPruebas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.CENTER, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.CENTER))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnImprimir.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setPreferredSize(new java.awt.Dimension(140, 40));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnPdf.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnPdf.setText("PDF");
        btnPdf.setPreferredSize(new java.awt.Dimension(140, 40));
        btnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPdfActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnAtras.setText("Atras");
        btnAtras.setPreferredSize(new java.awt.Dimension(140, 40));
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPdf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHojaPruebasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHojaPruebasMouseClicked
        ctxHP = modeloHojaPruebas.getListaHojaPruebas().get(tblHojaPruebas.getSelectedRow());
        HojaPruebasJpaController controller = new HojaPruebasJpaController();
        String estado = (controller.verificarHojaFinalizada(ctxHP));
        if (estado.equalsIgnoreCase("APROBADA")) {
            ctxHP.setAprobado("Y");
        }
        if (estado.equalsIgnoreCase("REPROBADA")) {
            ctxHP.setAprobado("N");
        }
        if (estado.equalsIgnoreCase("PENDIENTE")) {
            ctxHP.setFinalizada("N");
        }
        ModeloTablaPruebas.cntTest = 0;
        ModeloTablaPruebas.cntColum = 0;
        modeloPruebas.setListPruebas(ctxHP.getListPruebas());
        idHojaPrueba = ctxHP.getId();
    }//GEN-LAST:event_tblHojaPruebasMouseClicked

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        consultarVehiculo();
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        idHojaPrueba = -1;
        txtPlaca.setText("");
        modeloHojaPruebas.setListaHojaPruebas(new ArrayList<HojaPruebas>());
        modeloPruebas.setListPruebas(new ArrayList<Prueba>());
        ViewManager.getInstance().showPrincipal();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void txtPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPlacaKeyTyped
        evt.setKeyChar(Character.toUpperCase(evt.getKeyChar()));
        if (txtPlaca.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPlacaKeyTyped

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        impresionReporte = new ImpresionReporte();
        impresionReporte.setNumeroHojaPrueba(idHojaPrueba);
        impresionReporte.setImprimirPdf(false);
        impresionReporte.preguntarConsecutivos(this.ctxHP);
    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPdfActionPerformed
        impresionReporte = new ImpresionReporte();
        impresionReporte.setNumeroHojaPrueba(idHojaPrueba);
        impresionReporte.setImprimirPdf(true);
        impresionReporte.preguntarConsecutivos(this.ctxHP);
    }//GEN-LAST:event_btnPdfActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        consultarVehiculo();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void tblPruebasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPruebasMouseMoved
      
    }//GEN-LAST:event_tblPruebasMouseMoved

    

    private void consultarVehiculo() 
    {
        if (txtPlaca.getText().length() < 5) {
            Mensajes.mensajeAdvertencia("Que pena pero La placa debe tener 6 o mas caracteres");
            return;
        }
        Vehiculo vehiculo;
        idHojaPrueba = -1;
        vehiculo = new VehiculoJpaController().findVehiculosByPlaca(txtPlaca.getText());
        if (vehiculo == null) {
            Mensajes.mensajeAdvertencia("No existe vehiculo con placa " + txtPlaca.getText());
            modeloHojaPruebas.setListaHojaPruebas(new ArrayList<HojaPruebas>());
            modeloPruebas.setListPruebas(new ArrayList<Prueba>());
            txtPlaca.setText("");
            txtPlaca.requestFocus();
            return;
        }
        modeloHojaPruebas.setListaHojaPruebas(vehiculo.getHojaPruebasList());
        if (!modeloHojaPruebas.getListaHojaPruebas().isEmpty()) {
            ctxHP = modeloHojaPruebas.getListaHojaPruebas().get(0);
            tblHojaPruebas.setRowSelectionInterval(0, 0);
            try {
                ModeloTablaPruebas.cntTest = 0;
                ModeloTablaPruebas.cntColum = 0;
                modeloPruebas.setListPruebas(ctxHP.getListPruebas());
            } catch (Throwable e) {

            }
            idHojaPrueba = ctxHP.getId();
        }
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame();
        frame.getContentPane().add(new PanelImpresionByPlaca());
        frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        frame.setVisible(true);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnPdf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tblHojaPruebas;
    private javax.swing.JTable tblPruebas;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
